### ISSUE TITLE
Paramenter "scope" must be of type array, string used

### ISSUE THREAD

**Issue by ozeberle** [vishwac09/authzero#1] opened 2022-03-10 19:57 UTC
Hey man, first of all let me tell you: "Great job"!

And here comes my issue:
After setup the module, I go to /auth0/login, I receive an error message:

NOTICE: PHP message: Uncaught PHP Exception Auth0\SDK\Exception\ConfigurationException: "Parameter "scope" must be of type array, string used" at /opt/drupal/vendor/auth0/auth0-php/src/Exception/ConfigurationException.php line 125

Did I miss something?

**Comment by vishwac09** [comment] 2022-03-11 03:59
@ozeberle thanks for pointing this out, may i know the version of auth0/auth0-php library you have installed. I have tested this with auth0/auth0-php:7.5 version

**Comment by ozeberle** [comment] 2022-03-11 11:12
Of course. I've tried 7.5 and the lastest.

**Comment by vishwac09** [comment] 2022-03-11 13:27
@ozeberle i checked again but not able to reproduce it, if possible add the complete steps so i can check. Else if possible please raise a pull request with the fix, i believe this is raised in the following file AuthZeroSerivce.php line 43.

Also you can review the pull request https://github.com/vishwac09/authzero/pull/2 with some requirement fixes.

**Comment by vishwac09** [comment] 2022-03-11 14:56
released 1.0.1 version of module, do check for the issue once

**Comment by ozeberle** [comment] 2022-03-11 15:49
Thanks @vishwac09! I will let you know if have any issue.

**Comment by vishwac09** [comment] 2022-03-17 06:19
@ozeberle good to close this issue

**Closed** 2022-03-18 05:54 UTC
Labels: good first issue
